
export const ROUTE_NAMES = {
    LOGIN: '/iniciar-sesion',
    REGISTER: '/registrarse',
    RESET_PASSWORD: '/restablecer-contrasena',
    RESET_PASSWORD_CONFIRMATION: '/restablecer-contrasena-confirmacion',
    CONFIRM_ACCOUNT: '/confirmar-cuenta',
    NEW_PASSWORD: '/nueva-contrasena',
    PASSWORD_UPDATED: '/contrasena-actualizada',
    HOME: '/',
    HABITS_DETAIL: '/mis-habitos',
    HABITS_CREATE: '/mis-habitos/crear',
    HABITS_EDIT: '/mis-habitos/editar/:habitId',
    PROFILE: '/mi-perfil',
    PROFILE_EDIT: '/mi-perfil/editar',
    CHANGE_PASSWORD: '/mi-perfil/cambiar-contrasena',
    PROGRESS: '/progreso',
    BENEFITS_DETAIL: '/progreso/beneficios',
    COMMUNITY: '/comunidades',
    COMMUNITY_CREATE: '/comunidades/crear',
    COMMUNITY_CREATE_STEP_2: '/comunidades/crear/paso2',
    COMMUNITY_CREATE_STEP_3: '/comunidades/crear/paso3',
    FRIENDS: '/amigos',
    USERS: '/usuarios',
    NEWS: '/novedades',
};
