
export const ROUTE_NAMES = {
    LOGIN: '/iniciar-sesion',
    REGISTER: '/registrarse',
    RESET_PASSWORD: "/restablecer-contrasena",
    RESET_PASSWORD_CONFIRMATION: "/restablecer-contrasena-confirmacion",
    CONFIRM_ACCOUNT: "/confirmar-cuenta",
    NEW_PASSWORD: '/nueva-contrasena',
    PASSWORD_UPDATED: '/contrasena-actualizada',
    HOME: '/',
    HABITS_CREATE: '/mis-habitos/crear',
    HABITS_EDIT: '/mis-habitos/editar/:habitId',
    PROFILE: '/mi-perfil',
    PROFILE_EDIT: '/mi-perfil/editar',
    CHANGE_PASSWORD: '/mi-perfil/cambiar-contrasena',
    PROGRESS: '/progreso',
    BENEFITS_DETAIL: '/progreso/beneficios',
    COMMUNITY: '/comunidades',
    NEWS: '/novedades',
};